[package]
name = "serial_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.6.1"
color-eyre = "0.6.5"
crossterm = "0.29.0"
rand = "0.9.2"
ratatui = "0.29.0"
regex = "1.12.2"
serde = "1.0.228"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
tokio-serial = "5.4.5"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
