[package]
name = "serial_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3"
chrono = "0.4"
crossterm = "0.29"
rand = "0.9"
ratatui = "0.29"
regex = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tokio-serial = "5.4"
toml = "0.8"
