[package]
name = "serial_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
crossterm = "0.29"
rand = "0.9"
ratatui = "0.29"
regex = "1"
serde = { version = "1", features = ["derive"] }
serialport = { version = "4.8.1", features = ["serde"] }
thiserror = "2.0.17"
toml = "0.8"

[dev-dependencies]
tempfile = "3"
