# --- defaults ---
# baud_rate = 115200
# data_bits = 8          # 5, 6, 7, 8
# stop_bits = 1          # 1, 2
# parity = "none"        # none, odd, even
# flow_control = "none"  # none, software, hardware
# line_ending = "\n"     # "\n", "\r\n", "\r"

[USB0]
path = "/dev/ttyUSB0"
baud_rate = 115200
data_bits = 8
stop_bits = 1
parity = "none"
flow_control = "none"
line_ending = "\n"
color = "green"

[USB1]
path = "/dev/ttyUSB1"
baud_rate = 9600

[ACM0]
path = "/dev/ttyACM0"
baud_rate = 115200
color = "blue"
